---
- name: Install NTP
  yum:
    name: ntp
    state: latest

- name: Ship NTP config
  template:
    src: ntp.conf.j2
    dest: /etc/ntp.conf
    owner: root
    group: root
    mode: 0644

- name: Configure firewalld
  firewalld:
    service: ntp
    state: enabled
    immediate: true
    permanent: true
