### This playbook configures a braggi host to be a Jenkins slave.

- hosts:
    - braggi
    - incerta
  become: true
  tasks:

  - set_fact:
      disk: /dev/sdb
    when: '"braggi" in ansible_hostname'

  - set_fact:
      disk: /dev/nvme0n1
    when: '"incerta" in ansible_hostname'

  - name: Create jenkins-build home dir
    file:
      path: /home/jenkins-build
      state: directory

  - name: Install xfsprogs (Ubuntu)
    package:
      name: xfsprogs
      state: latest
    when: ansible_os_family == "Debian"

  - name: Unmount
    mount:
      path: /home/jenkins-build
      src: "{{ disk }}"
      state: unmounted
      fstype: xfs
    ignore_errors: true

  - name: Zap disk
    command: "sgdisk -Z {{ disk }}"

  - name: Configure disk
    filesystem:
      fstype: xfs
      dev: "{{ disk }}"

  - name: Mount disk
    mount:
      path: /home/jenkins-build
      src: "{{ disk }}"
      state: mounted
      fstype: xfs
